### PR TITLE
fix(toml): remove deprecated `only_sort_tables`

### LINKED ISSUE #133: `only_sort_tables` has been deprecated
Error:

```
TomlSort.__init__() got an unexpected keyword argument 'only_sort_tables'
```

The latest `toml-sort` module uses the new `CommentConfiguration`, `SortConfiguration` and `FormattingConfiguration` as parameters. See related PR [here](https://github.com/pappasam/toml-sort/pull/33).

### PR DESCRIPTION
**Pull request by liblaf**
fix #133

### CODE REVIEW

**Comment by macisamuele** [comment]
thanks for fixing it.
if tests are green, the pr will be automatically merge and I will release a new version later today or tomorrow

**Comment by macisamuele** [comment]
Merged as I do expect that test failures are caused by tox upgrade (fixed in #141).
If test failures are going to continue I'm going to take it to stability.
Thanks for the contribution.
